### ISSUE TITLE
Improve script_api file handling in the editor

### ISSUE THREAD

**Issue by britzl** [defold/defold#6794]
The `.script_api` file handling in the editor needs to be improved to support existing module/namespace names such as `go.*` and `gui.*`. A good example of this is for `extension-spine` where the extension adds new gui functions to  the `gui` module.

For `extension-spine` we do not currently have any `.script_api` documentation for the gui functions. We want to add a `spine_gui.script_api` with the name set to `gui`:

```
- name: gui
  type: table
  desc: Functions and constants for interacting with Spine models in GUI

  members:
  - name: play_spine_anim
    type: function
    desc: Plays the specified animation on a Spine node.
```

This does however not work at the moment and the functions are not added to the autocomplete for gui.*.
